services:
  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=averysecurepassword
