### GET all blogs
GET localhost:3000/blogs

### GET specific blog with id
GET localhost:3000/blogs/1

### POST (create) a new blog
POST localhost:3000/blogs/new
Content-Type: application/json

{
  "author": "Michael",
  "details": "A blog..."
}

### DELETE a blog
DELETE localhost:3000/blogs/1

### PATCH/UPDATE a blog
PATCH  localhost:3000/blogs/1
Content-Type: application/json

{
  "author": "MaikkunDev",
  "details": "A blog about ..."
}